# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_rCIW <- function(nu, S, fix, eps) {
    .Call(`_moprobit_internal_rCIW`, nu, S, fix, eps)
}

internal_iter <- function(prior, iters, TMN_iters, fixSigma, fixCrossBlockCov, eps) {
    .Call(`_moprobit_internal_iter`, prior, iters, TMN_iters, fixSigma, fixCrossBlockCov, eps)
}

